# Permanent Service Configurations
# These services provide direct access without port-forwarding

---
# NodePort service for Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: observability
  labels:
    app: prometheus
    service-type: nodeport
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090  # Accessible at minikube-ip:30090
    protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus

---
# NodePort service for Grafana
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: observability
  labels:
    app: grafana
    service-type: nodeport
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300  # Accessible at minikube-ip:30300
    protocol: TCP
  selector:
    app.kubernetes.io/name: grafana

---
# LoadBalancer service for Istio Gateway (alternative to port-forward)
# Note: Your existing istio-demo-gateway-istio is already LoadBalancer
# This is just documentation of the existing service
# Accessible at 127.0.0.1:80 (already configured)