# Instructions: Add this scrape job to your existing prometheus.yml configuration
# in gateway/observability/observability-stack.yaml under the scrape_configs section

# Add this to the scrape_configs list in your Prometheus ConfigMap:

    # Vector metrics for Istio Gateway latency
    - job_name: 'vector-istio-gateway-metrics'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - vector
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: vector
      - source_labels: [__meta_kubernetes_service_port_name]
        action: keep
        regex: metrics
      - source_labels: [__meta_kubernetes_service_name]
        target_label: job
        replacement: vector-istio-gateway
      metrics_path: /metrics
      scrape_interval: 15s