# This file contains the scrape configuration to add to your existing Prometheus setup
# Add this job to your prometheus.yml scrape_configs section

scrape_configs:
  # Vector metrics scraping
  - job_name: 'vector-istio-gateway-metrics'
    static_configs:
      - targets: ['vector-metrics.vector:9598']
    metrics_path: /metrics
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'vector-istio-gateway'

# Alternative: If using Kubernetes service discovery
# scrape_configs:
#   - job_name: 'vector-istio-gateway-metrics'
#     kubernetes_sd_configs:
#     - role: service
#       namespaces:
#         names:
#         - vector
#     relabel_configs:
#     - source_labels: [__meta_kubernetes_service_label_app]
#       action: keep
#       regex: vector
#     - source_labels: [__meta_kubernetes_service_port_name]
#       action: keep
#       regex: metrics
#     - source_labels: [__meta_kubernetes_service_name]
#       target_label: job
#       replacement: vector-istio-gateway-metrics