---
# HTTPRoute for Service A - defines how traffic is routed to Service A
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: service-a-route
  namespace: default
  labels:
    app.kubernetes.io/name: service-a
    app.kubernetes.io/component: route
    service: service-a
  annotations:
    description: "Routes traffic to Service A"
spec:
  parentRefs:
  - name: demo-gateway
    namespace: default
    sectionName: http
  hostnames:
  - "demo.local"
  - "service-a.demo.local"
  - "api.demo.local"  # Additional hostname for API access
  rules:
  # Rule 1: Main API path
  - matches:
    - path:
        type: PathPrefix
        value: /api/service-a
    - path:
        type: Exact
        value: /service-a
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: X-Service
          value: service-a
        - name: X-Gateway-Time
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
    backendRefs:
    - name: service-a
      port: 8080
      weight: 100
  # Rule 2: Health check endpoint
  - matches:
    - path:
        type: PathPrefix
        value: /health/service-a
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /health
    backendRefs:
    - name: service-a
      port: 8080