# Istio Telemetry configuration for JSON access logging
# This enables access logging mesh-wide to match the observability from Envoy Gateway
# 
# Note: This only ENABLES access logging. The JSON format is configured via meshConfig
# using either:
#   1. ./setup-access-logging.sh (for existing Istio installations)
#   2. ./istio-install-with-logging.sh (for new Istio installations)
#
# The JSON format matches gateway/observability/envoy-observability.yaml exactly:
# timestamp, method, path, protocol, response_code, response_flags, bytes_received/sent,
# duration, upstream_service_time, x_forwarded_for, user_agent, request_id, authority,
# upstream_host/cluster, downstream_remote/local_address, route_name
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: istio-access-logging
  namespace: istio-system
spec:
  # Apply to all workloads in the mesh
  accessLogging:
  - providers:
    - name: envoy