# Telemetry API for access logging - Modern Istio approach
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: gateway-access-logging
  namespace: default
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: istio-demo-gateway
  accessLogging:
  - providers:
    - name: envoy
---
# Optional: Custom format using EnvoyFilter (if needed)
# This can be added later if the default format isn't sufficient
