apiVersion: v1
kind: Service
metadata:
  name: service-a-canary
  namespace: default
spec:
  selector:
    app: service-a
    version: v2
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP